# Generated by Django 4.2.16 on 2024-10-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hottrack", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="song",
            old_name="link_count",
            new_name="like_count",
        ),
    ]
